[error] examples/neg/lambdas/capability_closure.effekt:14:17: Captures {Get$capability} escape through return type () => Int at {Get$capability}
    def get() = resume(42)
                ^^^^^^^^^^
