[error] examples/neg/lambdas/closure.effekt:12:18: Captures {Yield$capability} escape through return type () => Unit at {Yield$capability}
  } with Yield { println("yielded!"); resume(()) }
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
